pipeline:
  name: Buildwebapp
  identifier: Buildwebapp
  projectIdentifier: FirstProject
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GItpatHarness
        build: <+input>
  stages:
    - stage:
        name: webbuild
        identifier: webbuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: buildwebresume
                  identifier: buildwebresume
                  spec:
                    connectorRef: DockerHub_connector
                    repo: sai143cool/mavenwebapp
                    tags:
                      - "1.0"
